[project]
name = "209as-number-line"
version = "0.1.0"
description = "Particle on a number line simulation with dynamics, noise, and crash probability"
readme = "README.md"
requires-python = ">=3.13.6"
dependencies = [
    "numpy>=1.24.0",
    "matplotlib>=3.7.0",
    "scipy>=1.16.2",
]
